title: Taufiq Bashori # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, my name is Taufiq and I'm Operations Manager in Gojek. 
  <br><br>
  I'm interested in all things analytics and Python 3.0 (pandas, numpy, seaborn, scikit-learn). 
  <br><br>
  <a href="https://www.linkedin.com/in/taufiq-bashori/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
